apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: system-virtual-service
spec:
  hosts:
  - "system.example.com"
  gateways:
  - sys-app-gateway
  http:
  - route:
    - destination:
        port:
          number: 9080
        host: system-service
    retries:
      attempts: 2
      retryOn: 5xx
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: inventory-virtual-service
spec:
  hosts:
  - "inventory.example.com"
  gateways:
  - sys-app-gateway
  http:
  - route:
    - destination:
        port:
          number: 9081
        host: inventory-service
    retries:
      attempts: 4
      retryOn: 5xx